
pub_sym_1:pub_sym_1.o
	gcc pub_sym_1.o -o pub_sym_1

pub_sym_1.o:pub_sym_1.c
	gcc -c  pub_sym_1.c

pub_sym_2:pub_sym_2.o
	gcc pub_sym_2.o -o pub_sym_2

pub_sym_2.o:pub_sym_2.c
	gcc -c pub_sym_2.c

buzy_waiting:buzy_waiting.o
	gcc buzy_waiting.o -o buzy_waiting

buzy_waiting.o:buzy_waiting.c
	gcc -c buzy_waiting.c 

clasic.c: clasic.o
	gcc clasic.o -o clasic

clasic.o:clasic.c
	gcc -c clasic.c


clean:
	rm -rf *.o pub_sym_1 pub_sym_2 buzy_waiting

