pthreads_detach_kill:pthreads_detach_kill.o
	gcc pthreads_detach_kill.o -o pthreads_detach_kill

pthreads_detach_kill.o:pthreads_detach_kill.c
	gcc -c pthreads_detach_kill.c

pthreads_sam:pthreads_sam.o
	gcc pthreads_sam.o -o pthreads_sam

pthreads_sam.o:pthreads_sam.c
	gcc -c pthreads_sam.c


pthreads_struktura: pthreads_struktura.o
	gcc pthreads_struktura.o -o pthreads_struktura

pthreads_struktura.o: pthreads_struktura.c
	gcc -c pthreads_struktura.c


clean:
	rm -rf *.o pthreads_detach_kill pthreads_sam pthreads_struktura
